version: '2.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: book_review_db
      MYSQL_USER: pravin
      MYSQL_PASSWORD: Demo12@Test23
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_NAME: book_review_db
      DB_USER: pravin
      DB_PASS: Demo12@Test23
      DB_DIALECT: mysql
      JWT_SECRET: mysecretkey
      ALLOWED_ORIGINS: http://<FRONTEND PUBLIC IP>:3000
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://<BACKEND PUBLIC IP>:3001
    ports:
      - "3000:3000"

volumes:
  mysql_data:
