version: "2.4"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: book_review_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_container
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: book_review_db
      DB_USER: appuser
      DB_PASS: apass
      DB_DIALECT: mysql
      PORT: 3001
      JWT_SECRET: mysecretkey
      ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000,http://52.7.27.251:3000"
      NODE_ENV: development
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: http://52.7.27.251:3001 
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - "3000:3000"

volumes:
  mysql_data:
